# Generated by Django 6.0 on 2025-12-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_coursesession_duration_override_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la campagne')),
                ('recipient_type', models.CharField(choices=[('COHORT', 'Cohort Spécifique'), ('ALL_ACTIVE', 'Tous les Étudiants Actifs'), ('ALL_STUDENTS', 'Tous les Étudiants (Actifs + Inactifs)')], max_length=20, verbose_name='Type de destinataires')),
                ('subject', models.CharField(max_length=255, verbose_name="Objet de l'email")),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='email_attachments/', verbose_name='Pièce jointe')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Nombre de destinataires')),
                ('success_count', models.IntegerField(default=0, verbose_name='Envois réussis')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Envois échoués')),
                ('recipient_emails', models.TextField(blank=True, verbose_name='Liste des emails (séparés par virgule)')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='academics.cohort', verbose_name='Cohort ciblé')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns_sent', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': "Campagne d'Email",
                'verbose_name_plural': "Campagnes d'Email",
                'ordering': ['-sent_at'],
            },
        ),
    ]
