# Generated by Django 6.0 on 2025-12-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='recipient_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Détails par destinataire'),
        ),
    ]
