# Generated by Django 6.0 on 2025-12-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_2', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, verbose_name='Pourquoi ?')),
                ('student_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_plan', models.CharField(choices=[('FULL', 'Totalité (Une fois)'), ('MONTHLY', 'Mensuel (Échéancier)'), ('PACK', "Pack d'Heures (Débit à la séance)")], default='FULL', max_length=10)),
                ('hours_purchased', models.DecimalField(decimal_places=1, default=0, help_text="Si Pack d'heures", max_digits=5)),
                ('hours_consumed', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.cohort')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.tariff', verbose_name='Tarif Appliqué')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'En Retard'), ('EXCUSED', 'Excusé')], default='PRESENT', max_length=10)),
                ('billable', models.BooleanField(default=True, verbose_name='Facturable (Déduire du pack)')),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.coursesession')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
