# Generated by Django 6.0 on 2025-12-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_discount_value_alter_installment_amount_and_more'),
        ('students', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='finance.discount'),
        ),
    ]
