# Generated by Django 6.0 on 2025-12-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacherprofile_payment_frequency'),
        ('students', '0004_student_id_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnnualFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1000)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_fees', to='core.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_fees', to='students.student')),
            ],
            options={
                'verbose_name': "Frais d'inscription annuel",
                'verbose_name_plural': "Frais d'inscription annuels",
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
