# Generated by Django 6.0 on 2026-01-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
