# Generated by Django 6.0 on 2025-12-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('TRANSFER', 'Virement (CCP/RIB)'), ('CHECK', 'Chèque')], default='CASH', max_length=10, verbose_name='Méthode de Paiement Préférée')),
                ('bank_details', models.CharField(blank=True, help_text='Numéro de compte pour virements', max_length=200, verbose_name='CCP/RIB')),
                ('tax_id', models.CharField(blank=True, help_text='Pour les déclarations fiscales', max_length=50, verbose_name="NIF (Numéro d'Identification Fiscale)")),
                ('notes', models.TextField(blank=True, help_text='Informations supplémentaires (contrat, horaires, etc.)', verbose_name='Notes Internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Professeur',
                'verbose_name_plural': 'Profils Professeurs',
            },
        ),
    ]
