# Generated by Django 6.0 on 2025-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Mensuel (à la fin du mois)'), ('BY_SESSION', 'Par séance (après chaque classe)')], default='MONTHLY', max_length=20, verbose_name='Fréquence de Paiement'),
        ),
    ]
