# Generated by Django 6.0 on 2025-12-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacherprofile_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Prix des frais d'inscription (DA)"),
        ),
    ]
