# Generated by Django 6.0 on 2025-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('PERCENT', 'Pourcentage (%)'), ('FIXED', 'Montant Fixe (DA)')], default='FIXED', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant dû')),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Virement/Carte'), ('CHECK', 'Chèque')], default='CASH', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Numéro de chèque ou virement', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total')),
            ],
        ),
    ]
