# Generated by Django 6.0 on 2025-12-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Début de Période')),
                ('period_end', models.DateField(verbose_name='Fin de Période')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total Payé (DA)')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('TRANSFER', 'Virement (CCP/RIB)'), ('CHECK', 'Chèque')], max_length=10, verbose_name='Méthode de Paiement')),
                ('payment_date', models.DateField(help_text='Date à laquelle le paiement a été effectué', verbose_name='Date de Paiement')),
                ('proof_reference', models.CharField(blank=True, help_text='N° de chèque, référence virement, etc.', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, help_text='Informations complémentaires sur ce paiement', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to=settings.AUTH_USER_MODEL, verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Paiement Professeur',
                'verbose_name_plural': 'Paiements Professeurs',
                'ordering': ['-payment_date'],
            },
        ),
    ]
