# Generated by Django 6.0 on 2025-12-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_teacherpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.IntegerField(verbose_name='Montant dû (DA)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(verbose_name='Montant (DA)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='amount',
            field=models.IntegerField(verbose_name='Montant Total (DA)'),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='total_amount',
            field=models.IntegerField(verbose_name='Montant Total Payé (DA)'),
        ),
    ]
