# Generated by Django 6.0 on 2025-12-16 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cohort_standard_price_and_more'),
        ('finance', '0004_alter_discount_value_alter_installment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCohortPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Début de Période')),
                ('period_end', models.DateField(verbose_name='Fin de Période')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement: Σ(durée_séance × tarif_horaire)', max_digits=10, verbose_name='Montant Dû (DA)')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Payé (DA)')),
                ('payment_date', models.DateField(verbose_name='Date de Paiement')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('TRANSFER', 'Virement (CCP/RIB)'), ('CHECK', 'Chèque')], max_length=10, verbose_name='Méthode de Paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payments', to='academics.cohort', verbose_name='Cohort/Groupe')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cohort_payments', to=settings.AUTH_USER_MODEL, verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Paiement Professeur par Cohort',
                'verbose_name_plural': 'Paiements Professeurs par Cohort',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['teacher', 'cohort', '-payment_date'], name='finance_tea_teacher_4532f6_idx'), models.Index(fields=['cohort', '-payment_date'], name='finance_tea_cohort__4f2f2c_idx')],
            },
        ),
    ]
