# Generated by Django 6.0 on 2025-12-16 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cohort_standard_price_and_more'),
        ('finance', '0005_teachercohortpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teachercohortpayment',
            constraint=models.UniqueConstraint(fields=('teacher', 'cohort', 'period_start', 'period_end', 'payment_date', 'amount_paid'), name='unique_cohort_payment_entry'),
        ),
    ]
