# Generated by Django 6.0 on 2026-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_teachercohortpayment_unique_cohort_payment_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='PDF, image (JPEG, PNG, WEBP)', null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='Reçu/Justificatif'),
        ),
    ]
