# Generated by Django 6.0 on 2026-01-20 12:28

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=timezone.now, help_text="Laissez vide pour utiliser la date d'aujourd'hui", verbose_name='Date de paiement'),
        ),
    ]
