# Generated by Django 6.0 on 2026-01-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_payment_date'),
        ('finance', '0009_alter_payment_date'),
    ]

    operations = [
    ]
