# Generated by Django 6.0 on 2025-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='Niveau')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source')),
                ('activity_type', models.CharField(blank=True, max_length=200, verbose_name="Type d'activité")),
                ('specific_course', models.CharField(blank=True, max_length=200, verbose_name='Cours spécifique')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('converted', models.BooleanField(default=False, verbose_name='Converti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
    ]
