# Generated by Django 6.0 on 2025-12-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('total_processed', models.IntegerField(verbose_name='Total traité')),
                ('created_count', models.IntegerField(verbose_name='Créés')),
                ('updated_count', models.IntegerField(verbose_name='Fusionnés')),
                ('duplicates_data', models.JSONField(default=list, verbose_name='Doublons détectés')),
                ('errors_data', models.JSONField(default=list, verbose_name='Erreurs')),
            ],
            options={
                'verbose_name': "Historique d'import",
                'verbose_name_plural': "Historiques d'import",
                'ordering': ['-created_at'],
            },
        ),
    ]
