# Generated by Django 6.0 on 2025-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_uploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='created_data',
            field=models.JSONField(default=list, verbose_name='Prospects créés'),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='updated_data',
            field=models.JSONField(default=list, verbose_name='Prospects fusionnés'),
        ),
    ]
