# Generated by Django 6.0 on 2025-12-18 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#6366f1', help_text='Couleur hex pour le visuel', max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Catégorie d'articles",
                'verbose_name_plural': "Catégories d'articles",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'article")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity_current', models.PositiveIntegerField(default=0, verbose_name='Quantité actuelle')),
                ('quantity_min', models.PositiveIntegerField(default=5, verbose_name='Quantité minimale (alerte)')),
                ('unit', models.CharField(default='pièce', max_length=50, verbose_name='Unité (pièce, boîte, pack...)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prix d'achat (€)")),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation (Bureau, Stockage...)')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Article obligatoire')),
                ('status', models.CharField(choices=[('in_stock', '✅ En stock'), ('low_stock', '⚠️ Stock faible'), ('out_of_stock', '❌ Rupture'), ('order_pending', '📦 En commande')], default='in_stock', max_length=20, verbose_name='Statut')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': "Article d'inventaire",
                'verbose_name_plural': "Articles d'inventaire",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la liste')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('event_date', models.DateField(blank=True, help_text='Pour quand est-ce que tu as besoin de ces articles ?', null=True, verbose_name="Date de l'événement/besoin")),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('status', models.CharField(choices=[('draft', '📝 Brouillon'), ('in_progress', '🔄 En cours'), ('completed', '✅ Complétée'), ('cancelled', '❌ Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût total estimé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes globales')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': "Liste d'achat",
                'verbose_name_plural': "Listes d'achat",
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item_name', models.CharField(blank=True, max_length=200, verbose_name='Nom personnalisé (si article non catalogué)')),
                ('quantity_needed', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit', models.CharField(default='pièce', max_length=50, verbose_name='Unité')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (€)')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Acheté')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('priority', models.IntegerField(choices=[(1, '🔴 Critique (URGENT)'), (2, '🟠 Haute'), (3, '🟡 Normale'), (4, '🔵 Basse'), (5, '⚪ Très basse (optionnel)')], default=3, verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='inventory.inventoryitem', verbose_name='Article existant')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shoppinglist', verbose_name="Liste d'achat")),
            ],
            options={
                'verbose_name': "Article de liste d'achat",
                'verbose_name_plural': "Articles de listes d'achat",
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
