# Generated by Django 6.0 on 2025-12-16 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('current_amount', models.IntegerField(default=0, verbose_name='Montant actuel (DA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reset', models.DateTimeField(blank=True, null=True, verbose_name='Dernier reset')),
            ],
            options={
                'verbose_name': 'Catégorie de caisse',
                'verbose_name_plural': 'Catégories de caisse',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Ajout (+)'), ('REMOVE', 'Retrait (-)'), ('SET', 'Définir le montant')], default='ADD', max_length=10)),
                ('amount', models.IntegerField(verbose_name='Montant (DA)')),
                ('note', models.TextField(blank=True, verbose_name='Note / Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount_before', models.IntegerField(verbose_name='Montant avant')),
                ('amount_after', models.IntegerField(verbose_name='Montant après')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cash.cashcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction de caisse',
                'verbose_name_plural': 'Transactions de caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
