# Generated by Django 6.0 on 2025-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashcategory',
            options={'ordering': ['-is_total', 'name'], 'verbose_name': 'Catégorie de caisse', 'verbose_name_plural': 'Catégories de caisse'},
        ),
        migrations.AddField(
            model_name='cashcategory',
            name='is_total',
            field=models.BooleanField(default=False, verbose_name='Catégorie TOTAL (calculée automatiquement)'),
        ),
    ]
