# Generated by Django 6.0 on 2025-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashcategory_options_cashcategory_is_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Ajout (+)'), ('REMOVE', 'Retrait (-)'), ('SET', 'Définir le montant'), ('RESET', 'Reset')], default='ADD', max_length=10),
        ),
    ]
