# Generated by Django 6.0 on 2025-12-25 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('backup_created', models.BooleanField(default=False)),
                ('backup_path', models.CharField(blank=True, max_length=500, null=True)),
                ('backup_message', models.TextField(blank=True)),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
