# Generated by Django 6.0 on 2026-01-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='backup_created',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='backup_message',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='backup_path',
        ),
    ]
