# Generated by Django 5.2.12 on 2026-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_synclog_backup_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
