# Generated by Django 6.0 on 2026-01-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date à laquelle cette tâche doit être faite', null=True, verbose_name='Date planifiée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, help_text='Date limite absolue', null=True, verbose_name='Date limite'),
        ),
    ]
