# Generated by Django 6.0 on 2025-12-15 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='Professeur Suppléant'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.cohort'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohort',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.level'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='academics.cohort'),
        ),
    ]
