# Generated by Django 6.0 on 2025-12-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='standard_price',
            field=models.IntegerField(default=0, verbose_name='Prix Standard (DA)'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='teacher_hourly_rate',
            field=models.IntegerField(default=0, help_text='Tarif appliqué pour chaque heure de cours de ce groupe', verbose_name='Tarif Horaire Prof (DA/h)'),
        ),
    ]
