# Generated by Django 6.0 on 2025-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_cohort_standard_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='Individuel'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='modality',
            field=models.CharField(choices=[('ONLINE', 'En ligne'), ('IN_PERSON', 'Présentiel')], default='IN_PERSON', max_length=10, verbose_name='Modalité'),
        ),
    ]
