# Generated by Django 6.0 on 2025-12-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_cohort_is_individual_cohort_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='duration_override_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
