# Generated by Django 6.0 on 2025-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_coursesession_duration_override_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(editable=False, help_text='Généré automatiquement', max_length=150),
        ),
    ]
