# Generated by Django 6.0 on 2025-12-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_cohort_name'),
        ('core', '0005_teacherprofile_payment_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Par défaut: Année académique active', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='core.academicyear'),
        ),
    ]
