# Generated by Django 6.0 on 2025-12-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_ramadan_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='ramadan_actual_minutes',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='ramadan_end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin pendant le Ramadan', null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='ramadan_start_time',
            field=models.TimeField(blank=True, help_text='Heure de début pendant le Ramadan', null=True),
        ),
    ]
