# Generated by Django 6.0 on 2025-12-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_cohort_substitute_teachers'),
        ('academics', '0010_remove_cohort_ramadan_actual_minutes_and_more'),
    ]

    operations = [
    ]
