# Generated by Django 6.0 on 2025-12-25 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_merge_20251223_1635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='Professeur Suppléant (Legacy)'),
        ),
    ]
