# Generated by Django 6.0 on 2026-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_cohort_substitute_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='teacher_hourly_rate_override',
            field=models.IntegerField(blank=True, help_text='Laissez vide pour utiliser le taux standard du cohort. Remplissez pour surcharger pour cette séance uniquement.', null=True, verbose_name='Taux Horaire Spécifique (DA/h)'),
        ),
    ]
