# Generated by Django 6.0 on 2026-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_coursesession_teacher_hourly_rate_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Abréviation unique du cohort (générée automatiquement)', max_length=20),        ),
    ]