# Generated by Django 6.0 on 2026-01-22 09:01

from django.db import migrations, models


def populate_abbreviations(apps, schema_editor):
    """Remplir le champ abbreviation pour tous les cohorts existants."""
    Cohort = apps.get_model('academics', 'Cohort')
    LANGUAGE_CODES = {
        # Langues principales
        'Chinois': 'CHN',
        'Mandarin': 'CHN',
        'Cantonais': 'CAN',
        'Japonais': 'JPN',
        'Coréen': 'KR',
        'Allemand': 'DEU',
        'Français': 'FRA',
        'Anglais': 'ENG',
        'Espagnol': 'ESP',
        'Portugais': 'PORT',
        'Italien': 'ITA',
        'Russe': 'RUS',
        'Arabe': 'ARA',
        'Turc': 'TUR',
        'Grec': 'GRE',
        'Suédois': 'SWE',
        'Norvégien': 'NOR',
        'Danois': 'DAN',
        'Néerlandais': 'NED',
        'Polonais': 'POL',
        'Roumain': 'ROM',
        'Ukrainien': 'UKR',
        'Vietnamien': 'VIE',
        'Thaï': 'THA',
        'Khmer': 'KHM',
        'Hindi': 'HIN',
        'Bengali': 'BEN',
        'Ourdou': 'URD',
        'Persan': 'PER',
        'Hébreu': 'HEB',
        'Swahili': 'SWA',
        'Indonésien': 'IND',
        'Malais': 'MAL',
        'Tagalog': 'TAG',
        'Coréen': 'KOR',
        # Ateliers et cours spécialisés
        'Calligraphie': 'CALL',
        'Peinture': 'PAINT',
        'Danse': 'DANCE',
        'Musique': 'MUS',
        'Théâtre': 'THEA',
        'Cuisine': 'COOK',
        'Informatique': 'IT',
        'Math': 'MATH',
        'Science': 'SCI',
        'Histoire': 'HIST',
        'Littérature': 'LIT',
    }
    
    MODALITY_CODES = {
        ('IN_PERSON', False): 'P',
        ('ONLINE', False): 'O',
        ('IN_PERSON', True): 'IP',
        ('ONLINE', True): 'IO',
    }
    
    updated_count = 0
    for cohort in Cohort.objects.all():
        try:
            # Récupérer le code de langue
            subject_name = cohort.subject.name.strip()
            language_code = LANGUAGE_CODES.get(subject_name)
            
            if not language_code:
                if len(subject_name) >= 3:
                    language_code = subject_name[:3].upper()
                else:
                    language_code = subject_name[:2].upper() + 'X'
            
            # Récupérer le niveau (numéro seulement)
            level_name = cohort.level.name.strip()
            level_number = ''.join(c for c in level_name if c.isdigit())
            if not level_number:
                level_number = '0'
            
            # Récupérer le code de modalité
            modality_key = (cohort.modality, cohort.is_individual)
            modality_code = MODALITY_CODES.get(modality_key, 'X')
            
            # Récupérer l'année et le mois
            year_short = str(cohort.start_date.year)[-2:]
            month_zero = f"{cohort.start_date.month:02d}"
            date_code = month_zero + year_short  # MMYY format
            
            # Construire l'abréviation
            abbreviation = f"{language_code}{level_number}{modality_code}{date_code}"
            
            # Mettre à jour seulement si vide
            if not cohort.abbreviation:
                cohort.abbreviation = abbreviation
                cohort.save(update_fields=['abbreviation'])
                updated_count += 1
        
        except Exception as e:
            print(f"Erreur pour cohort {cohort.id}: {e}")
    
    print(f"✅ {updated_count} cohorts ont été mis à jour avec une abréviation")


def reverse_abbreviations(apps, schema_editor):
    """Vider les abréviations (reverse)."""
    Cohort = apps.get_model('academics', 'Cohort')
    Cohort.objects.all().update(abbreviation='')


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_cohort_abbreviation'),
    ]

    operations = [
        migrations.RunPython(populate_abbreviations, reverse_abbreviations),
        migrations.AlterField(
            model_name='cohort',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Abréviation unique du cohort (générée automatiquement)', max_length=20, unique=True),
        ),
    ]
